name: Ejecutor de Tareas ETL

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  ejecutar-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Aseguramos la creación de la carpeta de logs
      - name: Crear directorio de logs
        run: mkdir -p logs

      # Cambiamos a la ejecución simple para ver si el error es de ruta
      - name: Ejecutar Recolector Crudo
        run: python src/etl/recolector_crudo.py

      - name: Ejecutar Agregador Horario
        run: python src/etl/agregador_horario.py

      - name: Guardar logs de ejecución
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs-ejecucion
          path: logs/
